### PR TITLE
ve and intital battery pass

### PR DESCRIPTION
**Pull request by bcormier1**

### CODE REVIEW

**Comment by bcormier1** [comment]
I'm using this as the baseline numbers https://www.tesla.com/sites/default/files/pdfs/powerwall/Powerwall%202_AC_Datasheet_en_northamerica.pdf

**Comment by andimorey** [comment]
Seems to be working as intended - however should we do something more than throwing an error for BatteryFullError or BatteryEmpty Error?

**Comment by bcormier1** [comment]
> Seems to be working as intended - however should we do something more than throwing an error for BatteryFullError or BatteryEmpty Error?

My thought was we could handle those errors gracefully in the driver. What did you have in mind?

**Comment by atox120** [comment]
Looks good, i had a few ideas for enhancements (such as including the round trip efficiency) - but I think I will hold off for now. 
I think as a next step, we could look at how it interacts when using live/historic data in a simulation, and in that process we can think about further enhancements being integrated.

**Pull request merged**
